config/routes.rb
Rails.application.routes.draw do
  get '/search' => "products#search"
  get '/current_cart' => "carts#show", :as => 'current_cart'
  post '/order' => "carts#order"
  post '/add_to_cart' => 'items#create', :as => 'add_to_cart'
  post '/update_cart_item' => 'items#update', :as => 'update_cart_item'
  post '/delete_cart_item' => 'items#destroy', :as => 'delete_cart_item'

  resources :carts, only: [:show]
  resources :products
  resources :items, only: [:create, :update, :destroy]
		
  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :items

  def add_item(params)
    product_id = params[:product_id]
    if items.none?{ |item| item.product_id == product_id }
      items.create!(params)
    else
      items.find{ |item| item.product_id == product_id }.increase_amount(params[:amount])
    end
  rescue StandardError => e
    errors.add(:base, "Could not add item to cart: " + e.message)
  end

  def total_sum
    items.inject(0){ |sum, item| sum + (item.amount * item.product.price) }
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  
  validates :amount, presence: true,
                    numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :enough_product_in_stock, on: [:create, :update]

  def increase_amount(additional_amount)
    total_amount = self.amount + additional_amount
    self.update!(amount: total_amount)
  end

  private
  def product_present
    if product_id.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end
		
  def enough_product_in_stock
    if amount_changed? && product.present? && product.stock < amount
      errors.add(:product, "#{product.name} has only #{product.stock} item(s) left in the stock.")
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  DEFAULT_MIN_PRODUCT_PRICE = 0
  DEFAULT_MAX_PRODUCT_PRICE = 1000

  validates :name, presence: true, uniqueness: true
  validates :price, numericality: { greater_than: 0 }
  validates :stock, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  self.per_page = 5

  def self.search_by(min_price, max_price, name, sort_by)
    search_result = Product.where('price > ? AND price < ? AND name like ?', min_price, max_price, "%#{name}%")
    sort_by.present? ? search_result.order(sort_by) : search_result
  end

  def purchase!(amount)
    return if amount == 0
    if stock < amount
      errors.add(:base, "Product '#{name}' has only #{stock} left in the stock.")
      return
    elsif amount < 0
      errors.add(:base, "Purchased amount cannot be negative!")
      return
    end
    self.stock -= amount
    save!
  end

  def restock!(restock_amount)
    return if restock_amount == 0
    if restock_amount < 0
      errors.add(:base, "Restock amount cannot be negative!")
      return
    end
    self.stock += restock_amount
    save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_cart

  before_action -> { current_cart }

  def current_cart
    # TODO: replace cart with current user
    if session[:cart_id].present?
      @cart ||= Cart.find_by_id(session[:cart_id])
      return @cart
    else
      @cart = Cart.create
      session[:cart_id] = @cart.id
      return @cart
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @items = (@cart.present? && @cart.items.present?) ? @cart.items : []
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @cart.add_item(item_params.transform_values!(&:to_i))

    if @cart.errors.present?
      flash[:error] = @cart.errors.full_messages.join(".")
      redirect_to products_path and return
    end

    flash[:notice] = "Cart was successfully updated."
    redirect_to current_cart
  end

  def update
    item_id = params.dig(:item, :item_id).to_i
    updated_amount_to_purchase = params.dig(:item, :amount).to_i
    render 'cart/show' and return if updated_amount_to_purchase == 0
    @cart.items.update!(item_id, amount: updated_amount_to_purchase)

    flash[:notice] = "Cart item was successfully updated."
    redirect_to current_cart
  rescue StandardError => e
    flash[:error] = e.message
    redirect_to current_cart
  end

  def destroy
    @cart.items.delete(params[:id])

    flash[:notice] = "Cart was successfully updated."
    redirect_to current_cart
  rescue StandardError => e
    flash[:error] = "Could not delete product from cart: #{e.message}."
    redirect_to current_cart
  end

  private
  def item_params
    params.expect(item: [:amount, :product_id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ProductHelper
  def index
    @products = Product.paginate(page: params[:page], per_page: 5)
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_path
  end

  # If user made a query by the beginning of the product name, displays products meeting the query.
  # Within the search (or in case user wants just to sort products) the products could be sorted in ascending order,
  # by name or by price.
  # User also could select product within particular price range.
  def search
    @products = []
    min_price = params.dig(:product, :price_min).present? ? params.dig(:product, :price_min) : min_products_price
    max_price = params.dig(:product, :price_max).present? ? params.dig(:product, :price_max) : max_products_price
    sort_by = if (params[:sorting_options] == "name")
                "name ASC"
              elsif (params[:sorting_options] == "price")
                "price ASC"
              else
                ""
              end

    @products = Product.search_by(min_price, max_price, params.dig(:product, :product_name), sort_by)
                  .paginate(page: params[:page], per_page: 5)
  rescue StandardError => e
    flash[:error] = "Could not perform search: #{e.message}."
    render 'search'
  end

  private
  def product_params
    params.expect(product: [:name, :stock, :price])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
  def min_products_price
    if Product.count > 0 && Product.minimum(:price).present?
      Product.minimum(:price).floor
    else
      Product::DEFAULT_MIN_PRODUCT_PRICE
    end
  end

  def max_products_price
    if Product.count > 0 && Product.maximum(:price).present?
      Product.maximum(:price).ceil
    else
      Product::DEFAULT_MAX_PRODUCT_PRICE
    end
  end
end

app/views/carts/_errors.html.erb
<% if @cart.present? && @cart.errors.any? %>
  <div id="error_explanation">
    <div>
      <ul class="errorText">
        <% @cart.errors.full_messages.each do |msg| %>
          <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/carts/show.html.erb
<div style="display: none;" id="minPV"><%= min_products_price %></div>
<div style="display: none;" id="maxPV"><%= max_products_price %></div>

<div align="center">
  <h1 class="header" align="center">Your cart<h1>
  <%= render "errors" %>
  <%= render "home/flash" %>
  <% if @items.size == 0%>
    <em class="plaintext"> No items in the cart</em>
  <% else %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col" class="text-center table-header">Product</th>
          <th scope="col" class="text-center table-header">Price</th>
          <th scope="col" class="text-center table-header">Purchase amount</th>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <th scope="row" class="plaintext align-middle text-center">
              <%= link_to item.product.name, product_path(item.product), class: 'custom-link'%>
            </th>
            <td class="plaintext align-middle text-center"><%= item.product.price %></td>
            <%= form_for :item, url: update_cart_item_path, method: "post" do |f| %>
              <td class="align-bottom">
                <%= f.number_field :amount, value: item.amount, class: 'form-control col-sm', min: 1 %>
              </td>
              <td class="align-bottom text-center">
                <%= f.hidden_field :item_id, value: item.id %>
                <% if item.product.stock >= 1 %>
                  <%= f.submit "Update", class: "btn btn-primary custom-btn", :disabled => false %>
                <% end %>
                <% if item.product.stock < 1 %>
                  <%= f.submit "Update", class: "btn btn-primary custom-btn custom-btn-disabled", :disabled => true %>
                <% end %>
              </td>
            <% end %>
            <td class="plaintext align-bottom text-center">
              <%= link_to "<button class='btn btn-primary custom-btn me-3'>Delete</button>".html_safe, item_path(item), method: :delete, data: {confirm: 'Are you sure you want to delete this item?'}, :id=>"delete-item-btn" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="cart-sum">
      <b><i>Total sum: </i></b><%= @cart.total_sum%>
    </div>
  <% end %>
</div>

app/views/goods/edit.html.erb
<h1 class="customHeader" align="center">Edit Product<h1>
<%= form_for :good, url: good_path(@good), method: :patch do |f| %>
	<div class="borderedDiv" align="center">
	
		<% if @good.errors.any? %>
		<div id="error_explanation">
		  <div align="center">
			<div class="errorHeader">
				<%= pluralize(@good.errors.count, "error") %> prohibited
			this article from being saved:
			</div>
			<div>
				<ul class="errorText">
					<% @good.errors.full_messages.each do |msg| %>
					<li>* <%= msg %></li>
					<% end %>
				</ul>
			</div>
		  </div>
		</div>
	  <% end %>
	
	<div>
		<%= f.label :name, class: 'plaintext'%><br>
		<%= f.text_field :name, class: 'customBorder' %>
	</div>
	
	<div>
		<%= f.label :stock, class: 'plaintext' %><br>
		<%= f.number_field :stock, min: 0, class: 'customBorder' %>
	</div>
	
	<div>
		<%= f.label :price, class: 'plaintext' %><br>
		<%= f.number_field :price, min: 0, step: 0.01, class: 'customBorder' %>
	</div>
	
	<div align="center" style="padding-top: 5pt; ">
		<div style="display: inline;">
			<%= f.submit class: 'customBtn' %>
		</div>
	
		<div style="display: inline;">
			<%= link_to "<button class='customBtn'>Back</button>".html_safe, goods_path, :id=>"backTo-catalog-btn" %>
		</div>
	</div>
	</div>
<% end %>


app/views/goods/new.html.erb
<h1 class="customHeader" align="center">New Product<h1>
<%= form_for :good, url: goods_path do |f| %>

	<% if @good.errors.any? %>
    <div id="error_explanation">
      <div align="center">
		<div class="errorHeader">
			<%= pluralize(@good.errors.count, "error") %> prohibited
        this article from being saved:
		</div>
		<div>
			<ul class="errorText">
				<% @good.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
				<% end %>
			</ul>
		</div>
      </div>
    </div>
  <% end %>
  
	<div class="borderedDiv" align="center">
	<div>
		<%= f.label :name, class: 'plaintext'%><br>
		<%= f.text_field :name, class: 'customBorder' %>
	</div>
	
	<div>
		<%= f.label :stock, class: 'plaintext' %><br>
		<%= f.number_field :stock, min: 0, class: 'customBorder' %>
	</div>
	
	<div>
		<%= f.label :price, class: 'plaintext' %><br>
		<%= f.number_field :price, min: 0, step: 0.01, class: 'customBorder' %>
	</div>
	
	<div align="center" style="padding-top: 5pt; ">
		<div style="display: inline;">
			<%= f.submit class: 'customBtn' %>
		</div>
	
		<div style="display: inline;">
			<%= link_to "<button class='customBtn'>Back</button>".html_safe, goods_path, :id=>"backTo-catalog-btn" %>
		</div>
	</div>
	</div>
<% end %>

app/views/goods/sorted.html.erb
<h1 class="customHeader" align="center">Product catalog</h1>

<div class="borderedDiv" align="center"> 
	<div> 
		<table class="plaintext">
			<tr>
				<th style="padding: 2pt 0pt 3pt 10pt;">Name of the product</th>
				<th style="padding: 2pt 0pt 3pt 10pt;">Price</th>
				<th style="padding: 2pt 0pt 3pt 10pt;">Amount in the stock</th>
				<th style="padding: 2pt 0pt 3pt 10pt;"/>
			</tr>
 
			<% @goods.each do |good| %>
				<tr>
					<td style="padding: 2pt 0pt 3pt 10pt;"><%= link_to good.name, good_path(good), class: 'goodsLink' %></td>
					<td style="padding: 2pt 0pt 3pt 10pt;"><%= good.price %></td>
					<td style="padding: 2pt 0pt 3pt 10pt;"><%= good.stock %></td>
					<td style="padding: 2pt 0pt 3pt 10pt;">Add to chart</td>
				</tr>
			<% end %>
			<% if @goods.size == 0%>
				<em class="plaintext"> No products in the catalog</em>
			<% end %>
		</table>
	</div>
	<div id="pagination" style="padding-top: 15pt;">
		<%= will_paginate(@users) %>
	</div>
	
	<div style="padding-top: 15pt;">
		<div style="padding-top: 15pt; display: inline;">
			<%= link_to "<button class='customBtn'>Add new product</button>".html_safe, new_good_path, :id=>"open-new-product-form-btn" %>
		</div>
		<div style="padding-top: 15pt; display: inline;">
			<%= link_to "<button class='customBtn'>Sort by name</button>".html_safe, goods_path(sorting_param: 'name'), method: :get, :id=>"sort-products-byname-btn" %>
		</div>
		<div style="padding-top: 15pt; display: inline;">
				<%= link_to "<button class='customBtn'>Sort by price</button>".html_safe, goods_path(sorting_param: 'price'), method: :get, :id=>"sort-products-byprice-btn" %>
		</div>
	</div>
	
	<div style="padding-top: 15pt; width: 50%;">
		<div class="plaintext" style="display: inline;" id="data1"></div>
		<div class="plaintext" style="display: inline;" id="data2"></div>
		<div id="the_slider"></div>
	</div>

</div>

app/views/home/_flash.html.erb
<% if flash[:error].present? %>
  <div class="alert alert-danger alert-margin plaintext alert-dismissible fade show" role="alert">
    <%= flash[:error] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if flash[:notice].present? %>
  <div class="alert alert-success alert-margin plaintext alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/home/_footer.html.erb
<div class="row gx-0 greenish-zigzag-bar container-padding footer">
  <p>2017 - <%= Date.today.year %></p>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark greenish-zigzag-bar">
  <div class="container-fluid">
    <%= link_to '', cart_path(:current_cart), class: 'nav-link cart glyphicon', :id=>"open-catalog-btn", method: :get %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to 'Home', root_path, class: 'nav-link active', :id=>"open-catalog-btn" %>
        <%= link_to 'Products', products_path, class: 'nav-link', :id=>"open-catalog-btn", method: :get %>
        <%= link_to 'Add new product', new_product_path, class: 'nav-link me-3', :id=>"open-new-product-form-btn", method: :get %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webshop</title>
	<meta content="text/html;charset=UTF-8" http-equiv="Content-Type"/>
	<meta content="UTF-8" http-equiv="encoding"/>
	<link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
	
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body style="overflow-x: none; overflow-y: scroll;">
	<%= render 'home/header' %>

	<div class="container-fluid container-padding">
	  <div class="main-content-margin">
	    <%= yield %>
	  </div>
	</div>

	<%= render 'home/footer' %>
  </body>
</html>

app/views/products/_errors.html.erb
<% if @product.present? && @product.errors.any? %>
  <div id="error_explanation">
    <div align="center">
      <div class="errorHeader">
        Product could not be saved due to <%= pluralize(@product.errors.count, "error") %>
      </div>
    <div>
      <ul class="errorText">
        <% @product.errors.full_messages.each do |msg| %>
          <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>
<% if @products.present? && @products.errors.any? %>
  <div id="error_explanation">
    <div align="center">
      <ul class="errorText">
        <% @products.errors.full_messages.each do |msg| %>
          <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/products/_form.html.erb
<%= form_for :product, url: products_path do |f| %>
  <%= render "errors" %>

  <div class="form-group row form-group-lg-margin">
    <%= f.label :name, class: 'col-sm-2 plaintext' %>
    <%= f.text_field :name, class: 'form-control col-sm customBorder', placeholder: 'Product name' %>
  </div>
  <div class="form-group row form-group-margin">
    <%= f.label :stock, class: 'col-sm-2 plaintext' %>
    <%= f.number_field :stock, min: 1, class: 'form-control col-sm customBorder' %>
  </div>
  <div class="form-group row form-group-margin">
    <%= f.label :price, class: 'col-sm-2 plaintext' %>
    <%= f.number_field :price, min: 0, step: 0.01, class: 'form-control col-sm customBorder' %>
  </div>
  <div class="form-group row form-group-lg-margin">
    <div class="col-sm-6 right-alignment">
      <%= link_to "<button class='btn btn-primary custom-btn'>Cancel</button>".html_safe, products_path, :id=>"backTo-catalog-btn" %>
    </div>
    <div class="col-sm-6">
      <%= f.submit class: 'btn btn-primary custom-btn' %>
    </div>
  </div>
<% end %>

app/views/products/_search_form.html.erb
<%= form_for :product, url: search_path, method: "get" do |f| %>
  <div class="row">
    <div class="col-2">
      <%= f.text_field :product_name, class: 'form-control', placeholder: 'Search for...' %>
    </div>
    <div class="col-4">
      <div class="input-group">
        <%= f.text_field :price_min, class: 'form-control', placeholder: "Min price: #{min_products_price}" %>
        <span class="input-group-text"> - </span>
        <%= f.text_field :price_max, class: 'form-control', placeholder: "Max price: #{max_products_price}" %>
      </div>
    </div>
    <div class="col-3">
      <%= select_tag "sorting_options", options_for_select([['Sort by name', 'name'], ['Sort by price', 'price'], ['None', '']], "Sort by name"), class: 'form-select' %>
    </div>
    <div class="col-1">
      <%= submit_tag("Search", class: 'btn btn-primary custom-btn top-alignment' )%>
    </div>
    <div class="col-2">
      <%= link_to "<button class='btn btn-primary custom-btn top-alignment'>Show all</button>".html_safe, products_path, method: :get, :id=>"show-all-productsbtn" %>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1 class="header" align="center">Edit Product<h1>
<%= render "form" %>

app/views/products/index.html.erb
<div style="display: none;" id="minPV"><%= min_products_price %></div>
<div style="display: none;" id="maxPV"><%= max_products_price %></div>

<div align="center">
  <h1 class="header" align="center">Products<h1>
  <div class="row text-center form-group-lg-margin">
    <%= render "search_form" %>
  </div>
  <%= render "home/flash" %>
  <% if @products.size == 0 %>
    <em class="plaintext"> No products in the catalog</em>
  <% else %>
    <table class="table table-hover products-table">
      <thead>
        <tr>
          <th scope="col" class="text-center table-header">Product</th>
          <th scope="col" class="text-center table-header">Price</th>
          <th scope="col" class="text-center table-header">Stock</th>
          <th scope="col" class="text-center table-header">Purchase amount</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <th scope="row" class="plaintext align-middle text-center">
              <%= link_to product.name, product_path(product), class: 'custom-link'%>
            </th>
            <td class="plaintext align-middle text-center"><%= product.price %></td>
            <td class="plaintext align-middle text-center"><%= product.stock%></td>
            <%= form_for :item, url: add_to_cart_path, method: "post" do |f| %>
              <td class="align-bottom">
                <%= f.number_field :amount, value: 1, class: 'form-control col-sm', min: 1 %>
              </td>
              <td class="align-bottom">
                <%= f.hidden_field :product_id, value: product.id %>
                <% if product.stock >= 1 %>
                  <%= f.submit "Add to Cart", class: "btn btn-primary custom-btn", :disabled => false %>
                <% end %>
                <% if product.stock < 1 %>
                  <%= f.submit "Add to Cart", class: "btn btn-primary custom-btn custom-btn-disabled", :disabled => true %>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="pagination custom-pagination">
      <%= will_paginate @products, :container => false %>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<h1 class="header" align="center">Add New Product<h1>
<%= render "form" %>

app/views/products/search.html.erb
<div style="display: none;" id="minPV"><%= min_products_price %></div>
<div style="display: none;" id="maxPV"><%= max_products_price %></div>

<div align="center">
  <h1 class="header" align="center">Products<h1>
  <div class="row text-center form-group-lg-margin">
    <%= render "search_form" %>
  </div>
  <%= render "home/flash" %>
  <% if @products.size == 0 %>
    <em class="plaintext"> No products in the catalog</em>
  <% else %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col" class="text-center table-header">Product</th>
          <th scope="col" class="text-center table-header">Price</th>
          <th scope="col" class="text-center table-header">Stock</th>
          <th scope="col" class="text-center table-header">Purchase amount</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <th scope="row" class="plaintext align-middle text-center">
              <%= link_to product.name, product_path(product), class: 'custom-link'%>
            </th>
            <td class="plaintext align-middle text-center"><%= product.price %></td>
            <td class="plaintext align-middle text-center"><%= product.stock%></td>
            <%= form_for :item, url: add_to_cart_path, method: "post" do |f| %>
              <td class="align-bottom">
                <%= f.number_field :amount, value: 1, class: 'form-control col-sm', min: 1 %>
              </td>
              <td class="align-bottom">
                <%= f.hidden_field :product_id, value: product.id %>
                <% if product.stock >= 1 %>
                  <%= f.submit "Add to Cart", class: "btn btn-primary custom-btn", :disabled => false %>
                <% end %>
                <% if product.stock < 1 %>
                  <%= f.submit "Add to Cart", class: "btn btn-primary custom-btn custom-btn-disabled", :disabled => true %>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="pagination custom-pagination">
      <%= will_paginate @products, :container => false %>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="product" align="center">
  <h1 class="header" align="center"><%= @product.name %></h1>
  <div class="plaintext product-desc-margin">
    <b>Price:</b>
    <%= @product.price%>
  </div>
  <div class="plaintext">
    <b>Stock amount:</b>
    <%= @product.stock%>
  </div>
</div>

<div class="text-center form-group-lg-margin">
  <div class="btn-group">
    <%= link_to "<button class='btn btn-primary custom-btn me-3'>Edit</button>".html_safe, edit_product_path, :id=>"edit-product-form-btn" %>
    <%= link_to "<button class='btn btn-primary custom-btn me-3'>Delete</button>".html_safe, product_path(@product), method: :delete, data: {confirm: 'Are you sure you want to delete this product?'}, :id=>"delete-product-form-btn" %>
    <%= link_to "<button class='btn btn-primary custom-btn me-3'>Back to the catalog</button>".html_safe, products_path, :id=>"open-catalog-btn" %>
  </div>
</div>
	
	
	
	